[build-system]
requires = ["setuptools >= 69.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mathinterpreter"
version = "0.1"

[project.optional-dependencies]
dev = [
    "ipython", 
    "pytest",
    ]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]